/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.impro.wordclockgenerator;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author patrick
 */
public class JFMain extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public JFMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPTimeToWords1 = new at.impro.wordclockgenerator.JPTimeToWords();
        jPWordsToGraph1 = new at.impro.wordclockgenerator.JPWordsToGraph();
        jPGraphToMatrix1 = new at.impro.wordclockgenerator.JPGraphToMatrix();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenue = new javax.swing.JMenu();
        jMISave = new javax.swing.JMenuItem();
        jMILoad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Time to Words", jPTimeToWords1);
        jTabbedPane1.addTab("Words to Graph", jPWordsToGraph1);
        jTabbedPane1.addTab("Graph to Matrix", jPGraphToMatrix1);

        jMenue.setText("File");

        jMISave.setText("Save");
        jMISave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISaveActionPerformed(evt);
            }
        });
        jMenue.add(jMISave);

        jMILoad.setText("Load");
        jMILoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILoadActionPerformed(evt);
            }
        });
        jMenue.add(jMILoad);

        jMenuBar1.add(jMenue);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISaveActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);

        try(FileOutputStream fs=new FileOutputStream(fc.getSelectedFile()))
        {
            try(ObjectOutputStream outStream= new ObjectOutputStream(fs)){
                jPTimeToWords1.save(outStream);
                outStream.close();
            } catch (Exception ex) {
                Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            fs.close();
        } catch (Exception ex) {
            Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMISaveActionPerformed

    private void jMILoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILoadActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        try(FileInputStream fs=new FileInputStream(fc.getSelectedFile()))
        {
            try(ObjectInputStream inStream= new ObjectInputStream(fs)){
                jPTimeToWords1.load(inStream);
                inStream.close();
            } catch (Exception ex) {
                Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            fs.close();
        } catch (Exception ex) {
            Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMILoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if(!System.getProperty("os.arch").contains("64")){
            JOptionPane.showMessageDialog(null, "This Program schuld be run on Java 64bit to avoid memory Problems!");
        }        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMILoad;
    private javax.swing.JMenuItem jMISave;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenue;
    private at.impro.wordclockgenerator.JPGraphToMatrix jPGraphToMatrix1;
    private at.impro.wordclockgenerator.JPTimeToWords jPTimeToWords1;
    private at.impro.wordclockgenerator.JPWordsToGraph jPWordsToGraph1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
